### ISSUE TITLE
Working with simulator

### ISSUE THREAD

**Issue by yoggi56** [mjbots/quad#4]
Hi!
I downloaded and compiled code using your instruction. 
When I run simulation by commands 
`./bazel-bin/simulator/simulator -c configs/quadruped.ini`
`http://localhost:4778`
I can see next things
![Screenshot from 2023-07-17 18-23-57](https://github.com/mjbots/quad/assets/22730342/85639826-a25c-407d-9583-cb8ea57fda0e)
![Screenshot from 2023-07-17 18-24-07](https://github.com/mjbots/quad/assets/22730342/7c122b51-33d8-473a-a672-cd4716a5aa65)

Could you tell me please how to force the robot to walk?

**Comment by jpieper** [comment]
That looks like a recently introduced bug.  Can you update to at least include this https://github.com/mjbots/quad/commit/20e0de0a6abc324b39f88084c0a2cb9ac590d95a and try again, then let me know if it is working?

**Comment by yoggi56** [comment]
Thank you! Now it works :)
